#!/bin/bash
current_index=`pacmd list-sinks|grep '* index:'|egrep -o '[0-9]+'`
max_index=`pacmd list-sinks|grep index:|tail -n1|egrep -o '[0-9]+'`
if [ $current_index == $max_index ]
then
  current_index=0
else
  current_index=$(( $current_index + 1 ))
fi

pacmd set-default-sink $current_index
for x in `pacmd list-sink-inputs|grep index|egrep -o '[0-9]+'`; do 
  pacmd move-sink-input $x $current_index; 
done

notify-send -u critical "Switched Sound" "`pacmd list-sinks | grep '* index' -A100 |grep device.profile.description|head -n1|egrep '\".*\"' -o`"

